/*
    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.
  
    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.
  
    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.
*/
// filtre pour les caractères admis dans les trames NMEA
//  GPGGA et GPRMC qui sont seules demandées au GPS L80
// Info trouvé dans:
// https://docs.novatel.com/oem7/Content/Logs/NMEA_Standard_Logs_.htm
// https://docs.novatel.com/oem7/Content/Logs/GPGGA.htm
// https://docs.novatel.com/oem7/Content/Logs/GPRMC.htm
// Seuls ces caractères semblent valides
// pour les entête:  GPRMC  GPGGA  GNRMC  GNGGA
//  A D E M N S V W  .  ,  *  $  [CR]  [LF]
//  les chiffres et les caractères A à F pour checksum en hexa
// Les caractères > à 0x57  (W) sont interdits,
//  les autres si il y a 1 dans la table sont OK
// Dans la table 1 caractères permis,  0interdit
char asciiFilter[] = {
  0,  // 0x00 ascii code  0 NULL  (Null character)
  0,  // 0x01 ascii code  1 SOH (Start of Header)
  0,  // 0x02 ascii code  2 STX (Start of Text)
  0,  // 0x03 ascii code  3 ETX (End of Text)
  0,  // 0x04 ascii code  4 EOT (End of Transmission)
  0,  // 0x05 ascii code  5 ENQ (Enquiry)
  0,  // 0x06 ascii code  6 ACK (Acknowledgement)
  0,  // 0x07 ascii code  7 BEL (Bell)
  0,  // 0x08 ascii code  8 BS  (Backspace)
  0,  // 0x09 ascii code  9 HT  (Horizontal Tab)
  1,  // 0x0A ascii code  10  LF  (Line feed)
  0,  // 0x0B ascii code  11  VT  (Vertical Tab)
  0,  // 0x0C ascii code  12  FF  (Form feed)
  1,  // 0x0D ascii code  13  CR  (Carriage return)
  0,  // 0x0E ascii code  14  SO  (Shift Out)
  0,  // 0x0F ascii code  15  SI  (Shift In)
  0,  // 0x10 ascii code  16  DLE (Data link escape)
  0,  // 0x11 ascii code  17  DC1 (Device control 1)
  0,  // 0x12 ascii code  18  DC2 (Device control 2)
  0,  // 0x13 ascii code  19  DC3 (Device control 3)
  0,  // 0x14 ascii code  20  DC4 (Device control 4)
  0,  // 0x15 ascii code  21  NAK (Negative acknowledgement)
  0,  // 0x16 ascii code  22  SYN (Synchronous idle)
  0,  // 0x17 ascii code  23  ETB (End of transmission block)
  0,  // 0x18 ascii code  24  CAN (Cancel)
  0,  // 0x19 ascii code  25  EM  (End of medium)
  0,  // 0x1A ascii code  26  SUB (Substitute)
  0,  // 0x1B ascii code  27  ESC (Escape)
  0,  // 0x1C ascii code  28  FS  (File separator)
  0,  // 0x1D ascii code  29  GS  (Group separator)
  0,  // 0x1E ascii code  30  RS  (Record separator)
  0,  // 0x1F ascii code  31  US  (Unit separator)
  0,  // 0x20 ascii code  32    (space)
  0,  // 0x21 ascii code  33  ! (exclamation mark)
  0,  // 0x22 ascii code  34  " (Quotation mark)
  0,  // 0x23 ascii code  35  # (Number sign)
  1,  // 0x24 ascii code  36  $ (Dollar sign)
  0,  // 0x25 ascii code  37  % (Percent sign)
  0,  // 0x26 ascii code  38  & (Ampersand)
  0,  // 0x27 ascii code  39  ' (Apostrophe)
  0,  // 0x28 ascii code  40  ( (round brackets or parentheses)
  0,  // 0x29 ascii code  41  ) (round brackets or parentheses)
  1,  // 0x2A ascii code  42  * (Asterisk)
  0,  // 0x2B ascii code  43  + (Plus sign)
  1,  // 0x2C ascii code  44  , (Comma)
  0,  // 0x2D ascii code  45  - (Hyphen)
  1,  // 0x2E ascii code  46  . (Full stop , dot)
  0,  // 0x2F ascii code  47  / (Slash)
  1,  // 0x30 ascii code  48  0 (number zero)
  1,  // 0x31 ascii code  49  1 (number one)
  1,  // 0x32 ascii code  50  2 (number two)
  1,  // 0x33 ascii code  51  3 (number three)
  1,  // 0x34 ascii code  52  4 (number four)
  1,  // 0x35 ascii code  53  5 (number five)
  1,  // 0x36 ascii code  54  6 (number six)
  1,  // 0x37 ascii code  55  7 (number seven)
  1,  // 0x38 ascii code  56  8 (number eight)
  1,  // 0x39 ascii code  57  9 (number nine)
  0,  // 0x3A ascii code  58  : (Colon)
  0,  // 0x3B ascii code  59  ; (Semicolon)
  0,  // 0x3C ascii code  60  < (Less-than sign )
  0,  // 0x3D ascii code  61  = (Equals sign)
  0,  // 0x3E ascii code  62  > (Greater-than sign ; Inequality)
  0,  // 0x3F ascii code  63  ? (Question mark)
  0,  // 0x40 ascii code  64  @ (At sign)
  1,  // 0x41 ascii code  65  A (Capital A )
  1,  // 0x42 ascii code  66  B (Capital B )
  1,  // 0x43 ascii code  67  C (Capital C )
  1,  // 0x44 ascii code  68  D (Capital D )
  1,  // 0x45 ascii code  69  E (Capital E )
  1,  // 0x46 ascii code  70  F (Capital F )
  1,  // 0x47 ascii code  71  G (Capital G )
  0,  // 0x48 ascii code  72  H (Capital H )
  0,  // 0x49 ascii code  73  I (Capital I )
  0,  // 0x4A ascii code  74  J (Capital J )
  0,  // 0x4B ascii code  75  K (Capital K )
  0,  // 0x4C ascii code  76  L (Capital L )
  1,  // 0x4D ascii code  77  M (Capital M )
  1,  // 0x4E ascii code  78  N (Capital N )
  0,  // 0x4F ascii code  79  O (Capital O )
  1,  // 0x50 ascii code  80  P (Capital P )
  0,  // 0x51 ascii code  81  Q (Capital Q )
  1,  // 0x52 ascii code  82  R (Capital R )
  1,  // 0x53 ascii code  83  S (Capital S )
  0,  // 0x54 ascii code  84  T (Capital T )
  0,  // 0x55 ascii code  85  U (Capital U )
  1,  // 0x56 ascii code  86  V (Capital V )
  1  // 0x57 ascii code  87  W (Capital W )
};
/*
  0,  // 0x58 ascii code  88  X (Capital X )
  0,  // 0x59 ascii code  89  Y (Capital Y )
  0,  // 0x5A ascii code  90  Z (Capital Z ) 1,  // 0x5B ascii code  91  [ (square brackets or box brackets)
  1,  // 0x5C ascii code  92  \ (Backslash)
  1,  // 0x5D ascii code  93  ] (square brackets or box brackets)
  1,  // 0x5E ascii code  94  ^ (Caret or circumflex accent)
  1,  // 0x5F ascii code  95  _ (underscore , understrike , underbar or low line)
  1,  // 0x60 ascii code  96  ` (Grave accent)
  1,  // 0x61 ascii code  97  a (Lowercase  a )
  1,  // 0x62 ascii code  98  b (Lowercase  b )
  1,  // 0x63 ascii code  99  c (Lowercase  c )
  1,  // 0x64 ascii code  100 d (Lowercase  d )
  1,  // 0x65 ascii code  101 e (Lowercase  e )
  1,  // 0x66 ascii code  102 f (Lowercase  f )
  1,  // 0x67 ascii code  103 g (Lowercase  g )
  1,  // 0x68 ascii code  104 h (Lowercase  h )
  1,  // 0x69 ascii code  105 i (Lowercase  i )
  1,  // 0x6A ascii code  106 j (Lowercase  j )
  1,  // 0x6B ascii code  107 k (Lowercase  k )
  1,  // 0x6C ascii code  108 l (Lowercase  l )
  1,  // 0x6D ascii code  109 m (Lowercase  m )
  1,  // 0x6E ascii code  110 n (Lowercase  n )
  1,  // 0x6F ascii code  111 o (Lowercase  o )
  1,  // 0x70 ascii code  112 p (Lowercase  p )
  1,  // 0x71 ascii code  113 q (Lowercase  q )
  1,  // 0x72 ascii code  114 r (Lowercase  r )
  1,  // 0x73 ascii code  115 s (Lowercase  s )
  1,  // 0x74 ascii code  116 t (Lowercase  t )
  1,  // 0x75 ascii code  117 u (Lowercase  u )
  1,  // 0x76 ascii code  118 v (Lowercase  v )
  1,  // 0x77 ascii code  119 w (Lowercase  w )
  1,  // 0x78 ascii code  120 x (Lowercase  x )
  1,  // 0x79 ascii code  121 y (Lowercase  y )
  1,  // 0x7A ascii code  122 z (Lowercase  z )
  1,  // 0x7B ascii code  123 { (curly brackets or braces)
  1,  // 0x7C ascii code  124 | (vertical-bar, vbar, vertical line or vertical slash)
  1,  // 0x7D ascii code  125 } (curly brackets or braces)
  1,  // 0x7E ascii code  126 ~ (Tilde ; swung dash)
  1,  // 0x7F ascii code  127 DEL (Delete)
  1,  // 0x80 ascii code  128 Ç (Majuscule C-cedilla )
  1,  // 0x81 ascii code  129 ü (letter "u" with umlaut or diaeresis ; "u-umlaut")
  1,  // 0x82 ascii code  130 é (letter "e" with acute accent or "e-acute")
  1,  // 0x83 ascii code  131 â (letter "a" with circumflex accent or "a-circumflex")
  1,  // 0x84 ascii code  132 ä (letter "a" with umlaut or diaeresis ; "a-umlaut")
  1,  // 0x85 ascii code  133 à (letter "a" with grave accent)
  1,  // 0x86 ascii code  134 å (letter "a"  with a ring)
  1,  // 0x87 ascii code  135 ç (Minuscule c-cedilla)
  1,  // 0x88 ascii code  136 ê (letter "e" with circumflex accent or "e-circumflex")
  1,  // 0x89 ascii code  137 ë (letter "e" with umlaut or diaeresis ; "e-umlaut")
  1,  // 0x8A ascii code  138 è (letter "e" with grave accent)
  1,  // 0x8B ascii code  139 ï (letter "i" with umlaut or diaeresis ; "i-umlaut")
  1,  // 0x8C ascii code  140 î (letter "i" with circumflex accent or "i-circumflex")
  1,  // 0x8D ascii code  141 ì (letter "i" with grave accent)
  1,  // 0x8E ascii code  142 Ä (letter "A" with umlaut or diaeresis ; "A-umlaut")
  1,  // 0x8F ascii code  143 Å (letter "A"  with a ring)
  1,  // 0x90 ascii code  144 É (Capital letter "E" with acute accent or "E-acute")
  1,  // 0x91 ascii code  145 æ (Latin diphthong "ae")
  1,  // 0x92 ascii code  146 Æ (Latin diphthong "AE")
  1,  // 0x93 ascii code  147 ô (letter "o" with circumflex accent or "o-circumflex")
  1,  // 0x94 ascii code  148 ö (letter "o" with umlaut or diaeresis ; "o-umlaut")
  1,  // 0x95 ascii code  149 ò (letter "o" with grave accent)
  1,  // 0x96 ascii code  150 û (letter "u" with circumflex accent or "u-circumflex")
  1,  // 0x97 ascii code  151 ù (letter "u" with grave accent)
  1,  // 0x98 ascii code  152 ÿ (letter "y" with diaeresis)
  1,  // 0x99 ascii code  153 Ö (letter "O" with umlaut or diaeresis ; "O-umlaut")
  1,  // 0x9A ascii code  154 Ü (letter "U" with umlaut or diaeresis ; "U-umlaut")
  1,  // 0x9B ascii code  155 ø (slashed zero or empty set)
  1,  // 0x9C ascii code  156 £ (Pound sign ; symbol for the pound sterling)
  1,  // 0x9D ascii code  157 Ø (slashed zero or empty set)
  1,  // 0x9E ascii code  158 × (multiplication sign)
  1,  // 0x9F ascii code  159 ƒ (function sign ; f with hook sign ; florin sign )
  1,  // 0xA0 ascii code  160 á (letter "a" with acute accent or "a-acute")
  1,  // 0xA1 ascii code  161 í (letter "i" with acute accent or "i-acute")
  1,  // 0xA2 ascii code  162 ó (letter "o" with acute accent or "o-acute")
  1,  // 0xA3 ascii code  163 ú (letter "u" with acute accent or "u-acute")
  1,  // 0xA4 ascii code  164 ñ (letter "n" with tilde ; enye)
  1,  // 0xA5 ascii code  165 Ñ (letter "N" with tilde ; enye)
  1,  // 0xA6 ascii code  166 ª (feminine ordinal indicator )
  1,  // 0xA7 ascii code  167 º (masculine ordinal indicator)
  1,  // 0xA8 ascii code  168 ¿ (Inverted question marks)
  1,  // 0xA9 ascii code  169 ® (Registered trademark symbol)
  1,  // 0xAA ascii code  170 ¬ (Logical negation symbol)
  1,  // 0xAB ascii code  171 ½ (One half)
  1,  // 0xAC ascii code  172 ¼ (Quarter or  one fourth)
  1,  // 0xAD ascii code  173 ¡ (Inverted exclamation marks)
  1,  // 0xAE ascii code  174 « (Guillemets or  angle quotes)
  1,  // 0xAF ascii code  175 » (Guillemets or  angle quotes)
  1,  // 0xB0 ascii code  176 ░
  1,  // 0xB1 ascii code  177 ▒
  1,  // 0xB2 ascii code  178 ▓
  1,  // 0xB3 ascii code  179 │ (Box drawing character)
  1,  // 0xB4 ascii code  180 ┤ (Box drawing character)
  1,  // 0xB5 ascii code  181 Á (Capital letter "A" with acute accent or "A-acute")
  1,  // 0xB6 ascii code  182 Â (letter "A" with circumflex accent or "A-circumflex")
  1,  // 0xB7 ascii code  183 À (letter "A" with grave accent)
  1,  // 0xB8 ascii code  184 © (Copyright symbol)
  1,  // 0xB9 ascii code  185 ╣ (Box drawing character)
  1,  // 0xBA ascii code  186 ║ (Box drawing character)
  1,  // 0xBB ascii code  187 ╗ (Box drawing character)
  1,  // 0xBC ascii code  188 ╝ (Box drawing character)
  1,  // 0xBD ascii code  189 ¢ (Cent symbol)
  1,  // 0xBE ascii code  190 ¥ (YEN and YUAN sign)
  1,  // 0xBF ascii code  191 ┐ (Box drawing character)
  1,  // 0xC0 ascii code  192 └ (Box drawing character)
  1,  // 0xC1 ascii code  193 ┴ (Box drawing character)
  1,  // 0xC2 ascii code  194 ┬ (Box drawing character)
  1,  // 0xC3 ascii code  195 ├ (Box drawing character)
  1,  // 0xC4 ascii code  196 ─ (Box drawing character)
  1,  // 0xC5 ascii code  197 ┼ (Box drawing character)
  1,  // 0xC6 ascii code  198 ã (letter "a" with tilde or "a-tilde")
  1,  // 0xC7 ascii code  199 Ã (letter "A" with tilde or "A-tilde")
  1,  // 0xC8 ascii code  200 ╚ (Box drawing character)
  1,  // 0xC9 ascii code  201 ╔ (Box drawing character)
  1,  // 0xCA ascii code  202 ╩ (Box drawing character)
  1,  // 0xCB ascii code  203 ╦ (Box drawing character)
  1,  // 0xCC ascii code  204 ╠ (Box drawing character)
  1,  // 0xCD ascii code  205 ═ (Box drawing character)
  1,  // 0xCE ascii code  206 ╬ (Box drawing character)
  1,  // 0xCF ascii code  207 ¤ (generic currency sign )
  1,  // 0xD0 ascii code  208 ð (lowercase "eth")
  1,  // 0xD1 ascii code  209 Ð (Capital letter "Eth")
  1,  // 0xD2 ascii code  210 Ê (letter "E" with circumflex accent or "E-circumflex")
  1,  // 0xD3 ascii code  211 Ë (letter "E" with umlaut or diaeresis ; "E-umlaut")
  1,  // 0xD4 ascii code  212 È (letter "E" with grave accent)
  1,  // 0xD5 ascii code  213 ı (lowercase dot less i)
  1,  // 0xD6 ascii code  214 Í (Capital letter "I" with acute accent or "I-acute")
  1,  // 0xD7 ascii code  215 Î (letter "I" with circumflex accent or "I-circumflex")
  1,  // 0xD8 ascii code  216 Ï (letter "I" with umlaut or diaeresis ; "I-umlaut")
  1,  // 0xD9 ascii code  217 ┘ (Box drawing character)
  1,  // 0xDA ascii code  218 ┌ (Box drawing character)
  1,  // 0xDB ascii code  219 █ (Block)
  1,  // 0xDC ascii code  220 ▄
  1,  // 0xDD ascii code  221 ¦ (vertical broken bar )
  1,  // 0xDE ascii code  222 Ì (letter "I" with grave accent)
  1,  // 0xDF ascii code  223 ▀
  1,  // 0xE0 ascii code  224 Ó (Capital letter "O" with acute accent or "O-acute")
  1,  // 0xE1 ascii code  225 ß (letter "Eszett" ; "scharfes S" or "sharp S")
  1,  // 0xE2 ascii code  226 Ô (letter "O" with circumflex accent or "O-circumflex")
  1,  // 0xE3 ascii code  227 Ò (letter "O" with grave accent)
  1,  // 0xE4 ascii code  228 õ (letter "o" with tilde or "o-tilde")
  1,  // 0xE5 ascii code  229 Õ (letter "O" with tilde or "O-tilde")
  1,  // 0xE6 ascii code  230 µ (Lowercase letter "Mu" ; micro sign or micron)
  1,  // 0xE7 ascii code  231 þ (capital letter "Thorn")
  1,  // 0xE8 ascii code  232 Þ (lowercase letter "thorn")
  1,  // 0xE9 ascii code  233 Ú (Capital letter "U" with acute accent or "U-acute")
  1,  // 0xEA ascii code  234 Û (letter "U" with circumflex accent or "U-circumflex")
  1,  // 0xEB ascii code  235 Ù (letter "U" with grave accent)
  1,  // 0xEC ascii code  236 ý (letter "y" with acute accent)
  1,  // 0xED ascii code  237 Ý (Capital letter "Y" with acute accent)
  1,  // 0xEE ascii code  238 ¯ (macron symbol)
  1,  // 0xEF ascii code  239 ´ (Acute accent)
  1,  // 0xF0 ascii code  240 ¬ (Hyphen)
  1,  // 0xF1 ascii code  241 ± (Plus-minus sign)
  1,  // 0xF2 ascii code  242 ‗ (underline or underscore)
  1,  // 0xF3 ascii code  243 ¾ (three quarters)
  1,  // 0xF4 ascii code  244 ¶ (paragraph sign or pilcrow)
  1,  // 0xF5 ascii code  245 § (Section sign)
  1,  // 0xF6 ascii code  246 ÷ (The division sign ; Obelus)
  1,  // 0xF7 ascii code  247 ¸ (cedilla)
  1,  // 0xF8 ascii code  248 ° (degree symbol )
  1,  // 0xF9 ascii code  249 ¨ (Diaeresis)
  1,  // 0xFA ascii code  250 • (Interpunct or space dot)
  1,  // 0xFB ascii code  251 ¹ (superscript one)
  1,  // 0xFC ascii code  252 ³ (cube or superscript three)
  1,  // 0xFD ascii code  253 ² (Square or superscript two)
  1,  // 0xFE ascii code  254 ■ (black square)
  1   // 0xFF ascii code  255 nbsp  (non-breaking space or no-break space)
*/
